### ISSUE TITLE
Coordinates resetting after reboot

### ISSUE THREAD

**Issue by ahskur** [zayronxio/Chaac-weather#1]
Hi,
Just installed the Widget and I'm pleased with the design.

I wanted to use the geographic coordinates instead of IP-based location - The problem happens after I give the latitude and longitude then reboot the system. 
It seems these parameters aren't being saved and/or loaded after rebooting.
So after powering the machine down and up again, I'm greeted with only ' ºC' without any numbers.
![desktop_widget](https://github.com/zayronxio/Chaac-weather/assets/63268217/92c65fd2-daff-47db-9302-11fd3734ba1a)

If I just give the parameters and apply, it works normally as expected.

I'm on EndeavourOS with KDE-Plasma.

Let me know if I can provide more information in any way.

**Comment by zayronxio** [comment]
The problem was replicated on my computer and I had the same error, after some modifications the error seems to have disappeared, try it yourself and if the error persists, reopen this issue

**Comment by ahskur** [comment]
Hello again,
Still having the same issue. Now I think the IP is acting as fallback? 
The coordinates get reset every time I reboot, but the Widget is at least showing something.
Could be that the coordinates are still saved but not updated in the GUI after a reboot?

**Comment by ahskur** [comment]
And just a quick thing: A person needs to be collaborator in the Repo to be able to reopen an issue, so it may be a good idea to wait some days before closing issues.
This avoids creating new Issues that reference older Issues that are still unsolved.

**Comment by zayronxio** [comment]
Ok, I would like to replicate the error, what coordinates are you trying to use?

**Comment by ahskur** [comment]
I'm trying the following coordinates obtained from [Open-Meteo](https://open-meteo.com/en/docs) :
Lat: 52.1277, Long: 11.6292

**Comment by zayronxio** [comment]
It seems to have been solved, please try again.
