### ISSUE TITLE
Fit size

### ISSUE THREAD

**Issue by cd-FileX** [zayronxio/Chaac-weather#11]
Like you should see on the screenshot, the size of the text is pretty small, to be exact too small to be readable.

Therefore, it should either adapt automatically to show the correct font size or the size should be settable.
![image](https://github.com/zayronxio/Chaac-weather/assets/79639219/f905d158-cbdb-4c04-80f5-b8165b489e94)

**Comment by zayronxio** [comment]
The widget is not created to be used in panel you can use the mininal-chaac instead
