### ISSUE TITLE
Display location issue 

### ISSUE THREAD

**Issue by Itz-Abhishek-Tiwari** [zayronxio/Chaac-weather#2]
![image](https://github.com/zayronxio/Chaac-weather/assets/69257109/7f6eb142-139c-4310-891b-dcf9e23b0b66)
I have been seeing the city displayed in this image in my KDE widget. Can you fix it?

**Comment by zayronxio** [comment]
I have added some corrections to the bash script to avoid the error you mention, please try again and open this issue again if the error persists
