### ISSUE TITLE
Floating Taskbar issue

### ISSUE THREAD

**Issue by HolySoap** [zayronxio/Chaac-weather#3]
Its about the **minimal chaac weather**.

The floating taskbar becomes non-floating when a program becomes maximised. 
Switching between those two modes creates an issue with the numbers (as seen in the pictures).
![Screenshot_2023-12-13_10:14:49](https://github.com/zayronxio/Chaac-weather/assets/65773051/4efb1466-e570-49c8-9634-cfd3373c3e5d)
![Screenshot_2023-12-13_10:15:37](https://github.com/zayronxio/Chaac-weather/assets/65773051/d8d4cec0-0b39-40a1-b405-ce20ce93b9f4)

There are three other issues I noticed with this widget.

1.  The reported weather icon isn't correct. In the pictures it shows "sunny" but in reality it should be "light rain" (checked with an Android app that uses Open-Meteo).
2. The "number" part and the "°C" part should have a space between them for better readability.
3. Maybe add an option without decimal numbers (rounding it).

**Comment by zayronxio** [comment]
The most recent version published on store.kde.org should work correctly, please try

**Comment by HolySoap** [comment]
Did install the update, did a restart and added a new widget but sadly no change.
Here is the proof that I use the newest version with the bug still in place.
![Screenshot_2023-12-15_07:41:00](https://github.com/zayronxio/Chaac-weather/assets/65773051/e2511c27-fee1-4314-a7c0-ef7d558a71cf)

**Comment by zayronxio** [comment]
make a new modification, try now

**Comment by HolySoap** [comment]
I tested it, I had about a second where it looked good, but then everything did go wrong.
Previously the widget also looked normal for a second before it acted strange with the numbers. Now instead of the numbers going crazy the whole taskbar became black and unresponsive, trying to remove the widget (dragging it out by guessing where it is) locked the desktop and made half of it black. I had to uninstall the widget to be able to remove this black thing.
![Screenshot_2023-12-17_06:11:06](https://github.com/zayronxio/Chaac-weather/assets/65773051/108bd654-9758-4def-b700-52c373a42ba3)
![Screenshot_2023-12-17_06:12:02](https://github.com/zayronxio/Chaac-weather/assets/65773051/07d3b548-aa12-4f11-845b-b931e98cfe88)

**Comment by zayronxio** [comment]
It is very strange, what distribution are you using? I will try to replicate the error

**Comment by HolySoap** [comment]
I going to copy it from the Infocenter. I think I have nothing out of the ordinary installed and my global theme is [this one](https://www.pling.com/p/1354062/).

Operating System: openSUSE Tumbleweed 20231215
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.112.0
Qt Version: 5.15.11
Kernel Version: 6.6.6-1-default (64-bit)
Graphics Platform: Wayland
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: AMD Radeon RX 7800 XT
Mesa version is 23.2.1

Two monitors are in use (LG 32GK650F over Display-port) if that matters at all.

**Comment by zayronxio** [comment]
After several tests it seems that it is already working correctly, I tested it in opensuse.

try the most recent version "0.7.5"

**Comment by HolySoap** [comment]
I told you that I had to uninstall the widget to remove this black blob, now I freshly installed it again and it works as it should.
Very strange behaviour and was a first to me, thank you for your time resolving it.
