### ISSUE TITLE
support qt6

### ISSUE THREAD

**Issue by als-creator** [zayronxio/Chaac-weather#5]
is there any plan to support qt6? beta version of kde wayland is already available, release in a month

**Comment by zayronxio** [comment]
yes, soon I will have a version for qt6

**Comment by als-creator** [comment]
and add to kde store?

**Comment by zayronxio** [comment]
Currently the widget is already added to the kde store, discover

**Comment by zayronxio** [comment]
https://raw.githubusercontent.com/zayronxio/Chaac-weather/main/installa-iamge/install.jpg

**Comment by zayronxio** [comment]
![install](https://github.com/zayronxio/Chaac-weather/assets/21132680/527735b8-a75e-4068-9d83-58c9b9b9730b)

**Comment by als-creator** [comment]
I see this https://store.kde.org/browse?cat=705&ord=latest

**Comment by zayronxio** [comment]
https://store.kde.org/p/2112055
