### ISSUE TITLE
There's no digits after a decimal point

### ISSUE THREAD

**Issue by iamalexei** [zayronxio/Chaac-weather#8]
After I had upgraded Minimal chaac weather to the 0.7.8 version the digits after a decimal point dissapeared:

![Screenshot_2024](https://github.com/zayronxio/Chaac-weather/assets/29608963/d0058669-e43f-4e9e-8c60-78f4dc81664f)

**Comment by iamalexei** [comment]
Just found out that the bug appears when the temperature is negative and there're 2 digits before a decimal point. For example, -14.5 °C is shown as -14. °C but -9.2 °C is correctly shown as -9.2 °C

**Comment by zayronxio** [comment]
try to solve it as soon as possible

**Comment by iamalexei** [comment]
> try to solve it as soon as possible

Than you! The issue is fixed in 0.7.9
