### ISSUE TITLE
Support Plasma 6

### ISSUE THREAD

**Issue by als-creator** [zayronxio/Chaac-weather#9]
![image](https://github.com/zayronxio/Chaac-weather/assets/25702710/4127a300-ec41-4756-b17c-60666ecada63)
![image](https://github.com/zayronxio/Chaac-weather/assets/25702710/ff367def-5b0d-4321-8d09-6c99587174d7)

This widget is not available in the KDE store for plasma 6, is it possible to add it there to the section forplasma 6 so that it is available for installation and will there be a version for plasma 6? Is it possible to add weather forecasts for several days for your widgets?
There is a compatibility problem between QT 5 and 6, so the widgets from QT 5 need to be improved
https://develop.kde.org/docs/plasma/widget/porting_kf6/

**Comment by zayronxio** [comment]
now available in plasma 6
